name: travel_organiser
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.1
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0
  intl: ^0.19.0
  firebase_core: ^2.30.0
  firebase_remote_config: ^4.4.2
  currency_picker: ^2.0.21
  fancy_shimmer_image: ^2.0.3
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

